[phases.setup]
# FFmpeg ကို System level မှာ ထည့်သွင်းခြင်း
nixPkgs = ["python3", "ffmpeg"]

[phases.build]
cmds = ["python -m pip install -r requirements.txt"]

[start]
# $PORT Error မတက်အောင် cmd ကို ဒီလိုရေးရပါမယ်
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
